version: '3.1'

services:

  php:
    image: php:7.1-cli
    restart: unless-stopped
    volumes:
      - /home/boneff/PhpstormProjects/primes:/var/www/html
    working_dir: /var/www/html
    stdin_open: true
    tty: true
    entrypoint: ./entrypoint.sh
