version: '3.1'

services:

  php:
    image: php:7.1-cli
    restart: unless-stopped
    volumes:
      - /var/www/html/primes:/var/www/html/primes
    working_dir: /var/www/html/primes
    stdin_open: true
    tty: true
    entrypoint: ./entrypoint.sh
